repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      # - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path, ./pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: "v0.31.0"
    hooks:
      - id: yapf
        args: [--style, ./setup.cfg, --in-place, --parallel]

  - repo: local
    hooks:
      - id: install-pkg-local
        name: install-pkg
        entry: install_pkg.sh
        always_run: true
        language: script
        pass_filenames: false
        stages:
          - push

  # - repo: https://github.com/pre-commit/mirrors-autopep8
  #   rev: 'v1.5.6'
  #   hooks:
  #   -   id: autopep8

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.812'
  #   hooks:
  #     - id: mypy
