name: "Check Code Format"

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pep8-check-flake8:
    if: false # always skip job
    name: Python formatting PEP8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install flake8
          pip list

      - name: Run checking
        run: flake8 .

  python-typing-mypy:
    name: Python typing check [mypy]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install mypy
        run: |
          pip install mypy==0.790
          pip list
      - name: mypy check
        run: |
          mypy
