name: Publish Docker Releases
# https://www.docker.com/blog/first-docker-github-action-is-here
# https://github.com/docker/build-push-action
on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build-conda:
    if: false # always skip job
    runs-on: ubuntu-latest
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
      fail-fast: false
      matrix:
        python_version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Publish main to Docker
        # only on pushes
        uses: docker/build-push-action@v1.1.0
        if: github.event_name == 'push'
        with:
          repository: DOCKER_AUTHOR_NAME/DOCKER_REPONAME
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockers/conda/Dockerfile
          build_args: PYTHON_VERSION=${{ matrix.python_version }}
          tags: "nightly-py${{ matrix.python_version }}"
        # The maximum number of minutes to let a job run before GitHub automatically cancels it. Default: 360
        timeout-minutes: 40

      - name: Get release version
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF##*/})

      - name: Publish Releases to Docker
        # only on releases
        uses: docker/build-push-action@v1.1.0
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          repository: DOCKER_AUTHOR_NAME/DOCKER_REPONAME
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockers/conda/Dockerfile
          build_args: PYTHON_VERSION=${{ matrix.python_version }},PACKAGE_VERSION=${{ env.RELEASE_VERSION }}
          tags: "${{ env.RELEASE_VERSION }}-py${{ matrix.python_version }},latest-py${{ matrix.python_version }}"
        # The maximum number of minutes to let a job run before GitHub automatically cancels it. Default: 360
        timeout-minutes: 40
