name: Greetings
# https://github.com/marketplace/actions/first-interaction

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, thanks for your contribution!, great first issue!'
        pr-message: 'Hey, thanks for the input! Please give us a bit of time to review it!'
