name: Install pkg

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pkg-install:
    if: false # always skip job
    runs-on: ${{ matrix.os }}
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
      fail-fast: false
      # max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest , windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare env
        run : |
          # pip install virtualenv
          # virtualenv vEnv
          # source vEnv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install "twine==3.2" setuptools wheel check-manifest

      - name: Create package
        run: |
          check-manifest
          # python setup.py check --metadata --strict
          python setup.py sdist bdist_wheel

      - name: Check package
        run: |
          twine check dist/*
          python setup.py clean

      - name: Install | Uninstall package - archive
        run: |
          # install as archive
          pip install dist/*.tar.gz
          cd ..
          python -c "import REPONAME as pkg ; print(pkg.__version__)"
          pip uninstall -y PACKAGENAME

      - name: Install | Uninstall package - wheel
        run: |
          # install as wheel
          pip install dist/*.whl
          cd ..
          python -c "import REPONAME as pkg ; print(pkg.__version__)"
          pip uninstall -y PACKAGENAME
