name: Install pkg

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pkg-check:
    if: false # always skip job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create package
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          # python setup.py check --metadata --strict
          python setup.py sdist bdist_wheel

      - name: Check package
        run: |
          pip install twine==1.13.0
          twine check dist/*
          python setup.py clean

  pkg-install:
    # if: false # always skip job
    runs-on: ${{ matrix.os }}
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
      fail-fast: false
      # max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest , windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          # python setup.py check --metadata --strict
          python setup.py sdist bdist_wheel

      - name: Install package
        run: |
          pip install virtualenv
          virtualenv vEnv
          source vEnv/bin/activate
          # pip install -r requirements/install.txt
          pip install dist/*
          cd .. & python -c "import PACKAGENAME as pkg ; print(pkg.__version__)"
          deactivate
          rm -rf vEnv
