name: "Unittests Windows"

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    if: false # always skip job
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip wheel
        pip install -r requirements/install.txt
        pip install -r requirements/unittests.txt
        pip install --no-deps .

    - name: Run Tests
      run: |
        coverage run -m unittest
        coverage xml # convert .coverage file to coverage.xml file

#COVERAGE_UPLOAD_CONFIG    - name: Upload coverage to Codecov
#COVERAGE_UPLOAD_CONFIG      uses: codecov/codecov-action@v1.0.2
#COVERAGE_UPLOAD_CONFIG      with:
#COVERAGE_UPLOAD_CONFIG        token: ${{secrets.CODECOV_TOKEN}} #required
#COVERAGE_UPLOAD_CONFIG        file: ./coverage.xml #optional
#COVERAGE_UPLOAD_CONFIG        flags: unittests #optional
#COVERAGE_UPLOAD_CONFIG        name: codecov-REPONAME #optional
